export const TERM_DETAIL_REQUEST = 'TERM_DETAIL_REQUEST';
export const TERM_DETAIL_SUCCESS = 'TERM_DETAIL_SUCCESS';
export const TERM_DETAIL_FAIL = 'TERM_DETAIL_FAIL';

export const TERM_LIST_REQUEST = 'TERM_LIST_REQUEST';
export const TERM_LIST_SUCCESS = 'TERM_LIST_SUCCESS';
export const TERM_LIST_FAIL = 'TERM_LIST_FAIL';
